version: 2.1
orbs:
  node: circleci/node@latest
  docker: circleci/docker@1.5.0
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: nhom6/docker-demo
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
        docker-password: 0mhbbnsbtcm
        docker-username: quyet
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: my_repo/orb-test
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  node-tests:
    jobs:
      - node/test
      - build-and-push
        requeries:
          - node/test
        filters:
          branches:
            only:
              - master
